#include <memory/CameraBlock.h>
#include <memory/FrameInfoBlock.h>
#include <memory/GameStateBlock.h>
#include <memory/JointBlock.h>
#include <memory/KickRequestBlock.h>
#include <memory/OdometryBlock.h>
#include <memory/SensorBlock.h>
#include <memory/WalkRequestBlock.h>
#include <memory/WalkResponseBlock.h>
#include <memory/WorldObjectBlock.h>
#include <memory/OpponentBlock.h>
#include <memory/BehaviorParamBlock.h>
#include <memory/JointCommandBlock.h>
#include <memory/WalkInfoBlock.h>
#include <memory/RobotStateBlock.h>
#include <memory/RobotVisionBlock.h>
#include <memory/BodyModelBlock.h>
#include <memory/SpeechBlock.h>
#include <memory/LocalizationBlock.h>
#include <memory/WalkParamBlock.h>
#include <memory/ALWalkParamBlock.h>
#include <memory/BehaviorBlock.h>
#include <memory/ImageBlock.h>
#include <memory/TeamPacketsBlock.h>
#include <memory/KickParamBlock.h>
#include <memory/ProcessedSonarBlock.h>
#include <memory/RobotInfoBlock.h>
#include <memory/AudioProcessingBlock.h>
