#ifndef VISIONBODYPOINTS_H
#define VISIONBODYPOINTS_H

/// @ingroup vision
enum VisionBodyPoints {
  LEFT_SHOULDER,
  RIGHT_SHOULDER,
  LEFT_FOOT_TL,
  LEFT_FOOT_TR,
  LEFT_FOOT_BL,
  LEFT_FOOT_BR,
  RIGHT_FOOT_TL,
  RIGHT_FOOT_TR,
  RIGHT_FOOT_BL,
  RIGHT_FOOT_BR,
  NUM_VISION_BODY_POINTS
};
#endif
