#!/usr/bin/env bash
# Installer Preamble #
DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source $DIR/common.sh
#--------------------#

echo Installing QT executables...
wget -N -r -l1 -nH --cut-dirs=2 --no-parent -e robots=off --accept="*-qt4" $NAO_LIBS/qmake32/
cp qmake32/qmake-qt4 $NAO_HOME/bin/
cp qmake32/moc-qt4 $NAO_HOME/bin/
cp qmake32/uic-qt4 $NAO_HOME/bin/
chmod +x $NAO_HOME/bin/qmake-qt4
chmod +x $NAO_HOME/bin/moc-qt4
chmod +x $NAO_HOME/bin/uic-qt4
