#!/bin/bash

TA="jphanna"

export NAO_HOME=~/nao/trunk

# 1. Check with user that you are about to remove ~/nao. Is this OK?
echo "About to set-up course codebase. This command will remove your ~/nao directory."

read -p "OK to proceed? " -r


if [[ ! $REPLY =~ ^[Yy]$ ]]
then
    exit 1
fi
echo "Removing ~/nao"

# 2. Remove ~/nao
if [ -d ~/nao ]
then
    rm -rf ~/nao
else
    echo "~/nao does not exist"
fi

# 3. Create new ~/nao directory
echo "Creating new ~/nao directory"
mkdir -p $NAO_HOME
cd $NAO_HOME

# 4. Pull in course code
echo "Cloning course repository."
git clone https://github.com/LARG/robotics-2015.git .

# 5. Create sym links to TA Naoqi and lib
echo "Creating sym links to TA's naoqi and lib"
ln -s "/home/$TA/nao/trunk/naoqi" $NAO_HOME/naoqi
ln -s "/home/$TA/nao/trunk/lib/alglib" $NAO_HOME/lib/alglib 
ln -s "/home/$TA/nao/trunk/lib/yaml-cpp" $NAO_HOME/lib/yaml-cpp 
ln -s "/home/$TA/nao/trunk/lib/flatbuffers" $NAO_HOME/lib/flatbuffers
#ln -s "/home/$TA/nao/trunk/lib/caffe" lib/caffe
ln -s "/home/$TA/nao/trunk/lib/fft" $NAO_HOME/lib/fft 

# 6. Sym links for Qmake
ln -s "/home/$TA/nao/trunk/bin/qmake-qt4" $NAO_HOME/bin/qmake-qt4
ln -s "/home/$TA/nao/trunk/bin/moc-qt4" $NAO_HOME/bin/moc-qt4
ln -s "/home/$TA/nao/trunk/bin/uic-qt4" $NAO_HOME/bin/uic-qt4


echo "export NAO_HOME=~/nao/trunk" >> ~/.bashrc
echo "source $NAO_HOME/install/bashrc_addenda" >> ~/.bashrc

echo "done"
